// Enhanced Demo Setup for ForkYouDaddy
// Creates impressive demo data for hackathon presentation

export interface DemoIP {
  id: string;
  title: string;
  description: string;
  content: string;
  contentType: 'text' | 'image' | 'audio' | 'video';
  license: string;
  author: string;
  createdAt: string;
  remixCount: number;
  revenue: string;
  cid: string;
  contentURI: string;
  parentId?: string;
  tags: string[];
  category: string;
  trending: boolean;
  views: number;
  likes: number;
}

export interface DemoUser {
  wallet_address: string;
  username: string;
  created_at: string;
  total_ips: number;
  total_remixes: number;
  followers_count: number;
  following_count: number;
  total_revenue: string;
  avatar_url?: string;
  bio?: string;
}

export interface DemoLicense {
  id: string;
  licenseId: string;
  ipId: string;
  buyerAddress: string;
  sellerAddress: string;
  price: number;
  purchaseDate: string;
  status: 'pending' | 'completed' | 'expired' | 'cancelled';
  transactionHash?: string;
  usageCount: number;
}

export interface DemoAnalytics {
  totalRevenue: string;
  totalRemixes: number;
  totalUsers: number;
  trendingIPs: number;
  totalViews: number;
  totalLicenses: number;
  averageRevenuePerIP: string;
  topEarningIP: string;
}

// WINNING DEMO DATA - Designed to impress judges
export const WINNING_DEMO_DATA = {
  ips: [
    {
      id: "viral-meme-1",
      title: "Pepe's Revenge - The Viral Sensation",
      description: "The meme that broke the internet and earned $50K in licensing revenue. A satirical take on crypto market crashes featuring Pepe as the protagonist.",
      content: "A satirical take on the crypto market with Pepe as the protagonist. The meme went viral across Twitter, Reddit, and TikTok, generating millions of views and thousands of remixes.",
      contentType: "image",
      license: "commercial",
      author: "0xAlice1234567890abcdef",
      createdAt: "2024-01-15T10:30:00Z",
      remixCount: 156,
      revenue: "0.5 ETH",
      cid: "QmDemo1",
      contentURI: "ipfs://QmDemo1",
      parentId: undefined,
      tags: ["meme", "crypto", "viral", "trending", "pepe"],
      category: "Art",
      trending: true,
      views: 2500000,
      likes: 45000
    },
    {
      id: "defi-strategy-1",
      title: "DeFi Yield Farming Masterclass",
      description: "The strategy that earned 200% APY and got remixed 89 times. Complete guide to maximizing yields across multiple protocols.",
      content: "Step-by-step guide to maximizing yields across multiple DeFi protocols. Includes risk management, impermanent loss protection, and advanced strategies for experienced traders.",
      contentType: "text",
      license: "enterprise",
      author: "0xBob9876543210fedcba",
      createdAt: "2024-01-14T15:45:00Z",
      remixCount: 89,
      revenue: "0.3 ETH",
      cid: "QmDemo2",
      contentURI: "ipfs://QmDemo2",
      parentId: undefined,
      tags: ["defi", "trading", "strategy", "yield", "farming"],
      category: "Education",
      trending: true,
      views: 1250000,
      likes: 23000
    },
    {
      id: "ai-art-collection-1",
      title: "AI-Generated Crypto Art Collection",
      description: "10,000 unique pieces generated by our AI, earning $25K in licensing. Each piece is unique and can be remixed by the community.",
      content: "Generative art collection with 10,000 unique pieces created using advanced AI algorithms. Each piece features unique traits and can be remixed by the community.",
      contentType: "image",
      license: "exclusive",
      author: "0xCharlieabcdef1234567890",
      createdAt: "2024-01-13T09:20:00Z",
      remixCount: 234,
      revenue: "0.8 ETH",
      cid: "QmDemo3",
      contentURI: "ipfs://QmDemo3",
      parentId: undefined,
      tags: ["nft", "art", "collection", "ai", "generative"],
      category: "Art",
      trending: true,
      views: 3500000,
      likes: 67000
    },
    {
      id: "remix-1",
      title: "Pepe's Revenge - Corporate Edition",
      description: "A corporate remix of the viral meme, adapted for business presentations and marketing campaigns.",
      content: "Professional adaptation of the viral Pepe meme for corporate use. Includes business-friendly versions and marketing templates.",
      contentType: "image",
      license: "commercial",
      author: "0xDavidfedcba9876543210",
      createdAt: "2024-01-16T14:20:00Z",
      remixCount: 45,
      revenue: "0.15 ETH",
      cid: "QmDemo4",
      contentURI: "ipfs://QmDemo4",
      parentId: "viral-meme-1",
      tags: ["meme", "corporate", "business", "marketing"],
      category: "Art",
      trending: false,
      views: 850000,
      likes: 12000
    },
    {
      id: "remix-2",
      title: "DeFi Strategy - Beginner's Guide",
      description: "Simplified version of the yield farming strategy for beginners.",
      content: "Beginner-friendly version of the DeFi yield farming strategy. Includes step-by-step instructions and safety tips.",
      contentType: "text",
      license: "personal",
      author: "0xEve1234567890abcdef",
      createdAt: "2024-01-17T11:15:00Z",
      remixCount: 23,
      revenue: "0.08 ETH",
      cid: "QmDemo5",
      contentURI: "ipfs://QmDemo5",
      parentId: "defi-strategy-1",
      tags: ["defi", "beginner", "guide", "tutorial"],
      category: "Education",
      trending: false,
      views: 450000,
      likes: 8900
    },
    {
      id: "audio-track-1",
      title: "Crypto Beats - The Sound of DeFi",
      description: "Original music track inspired by DeFi trading. Perfect for crypto content creators.",
      content: "Electronic music track with crypto-themed samples and beats. Ideal for YouTube videos, podcasts, and crypto content.",
      contentType: "audio",
      license: "commercial",
      author: "0xFrankabcdef1234567890",
      createdAt: "2024-01-12T16:30:00Z",
      remixCount: 67,
      revenue: "0.25 ETH",
      cid: "QmDemo6",
      contentURI: "ipfs://QmDemo6",
      parentId: undefined,
      tags: ["music", "crypto", "defi", "electronic"],
      category: "Music",
      trending: true,
      views: 1800000,
      likes: 34000
    }
  ],
  users: [
    {
      wallet_address: "0xAlice1234567890abcdef",
      username: "AliceCrypto",
      created_at: "2024-01-01T00:00:00Z",
      total_ips: 15,
      total_remixes: 45,
      followers_count: 1250,
      following_count: 89,
      total_revenue: "2.5 ETH",
      avatar_url: "https://images.pexels.com/photos/1234567/pexels-photo-1234567.jpeg",
      bio: "Crypto artist and meme creator. Making the internet laugh one meme at a time! 🐸"
    },
    {
      wallet_address: "0xBob9876543210fedcba",
      username: "BobTrader",
      created_at: "2024-01-02T00:00:00Z",
      total_ips: 8,
      total_remixes: 23,
      followers_count: 567,
      following_count: 34,
      total_revenue: "1.8 ETH",
      avatar_url: "https://images.pexels.com/photos/2345678/pexels-photo-2345678.jpeg",
      bio: "DeFi strategist and yield farmer. Sharing the best strategies! 📈"
    },
    {
      wallet_address: "0xCharlieabcdef1234567890",
      username: "CharlieArtist",
      created_at: "2024-01-03T00:00:00Z",
      total_ips: 12,
      total_remixes: 67,
      followers_count: 890,
      following_count: 45,
      total_revenue: "3.2 ETH",
      avatar_url: "https://images.pexels.com/photos/3456789/pexels-photo-3456789.jpeg",
      bio: "AI artist and NFT creator. Pushing the boundaries of digital art! 🎨"
    },
    {
      wallet_address: "0xDavidfedcba9876543210",
      username: "DavidCorp",
      created_at: "2024-01-04T00:00:00Z",
      total_ips: 5,
      total_remixes: 12,
      followers_count: 234,
      following_count: 23,
      total_revenue: "0.8 ETH",
      avatar_url: "https://images.pexels.com/photos/4567890/pexels-photo-4567890.jpeg",
      bio: "Corporate content creator. Making crypto accessible to businesses! 💼"
    },
    {
      wallet_address: "0xEve1234567890abcdef",
      username: "EveEducator",
      created_at: "2024-01-05T00:00:00Z",
      total_ips: 9,
      total_remixes: 34,
      followers_count: 456,
      following_count: 67,
      total_revenue: "1.2 ETH",
      avatar_url: "https://images.pexels.com/photos/5678901/pexels-photo-5678901.jpeg",
      bio: "Crypto educator. Making DeFi simple for everyone! 📚"
    }
  ],
  licenses: [
    {
      id: "license-1",
      licenseId: "commercial",
      ipId: "viral-meme-1",
      buyerAddress: "0xBob9876543210fedcba",
      sellerAddress: "0xAlice1234567890abcdef",
      price: 0.05,
      purchaseDate: "2024-01-16T12:00:00Z",
      status: "completed",
      transactionHash: "0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef",
      usageCount: 1
    },
    {
      id: "license-2",
      licenseId: "enterprise",
      ipId: "defi-strategy-1",
      buyerAddress: "0xCharlieabcdef1234567890",
      sellerAddress: "0xBob9876543210fedcba",
      price: 0.2,
      purchaseDate: "2024-01-17T14:30:00Z",
      status: "completed",
      transactionHash: "0xabcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890",
      usageCount: 1
    },
    {
      id: "license-3",
      licenseId: "exclusive",
      ipId: "ai-art-collection-1",
      buyerAddress: "0xDavidfedcba9876543210",
      sellerAddress: "0xCharlieabcdef1234567890",
      price: 1.0,
      purchaseDate: "2024-01-18T09:15:00Z",
      status: "completed",
      transactionHash: "0x7890abcdef1234567890abcdef1234567890abcdef1234567890abcdef123456",
      usageCount: 1
    },
    {
      id: "license-4",
      licenseId: "commercial",
      ipId: "audio-track-1",
      buyerAddress: "0xEve1234567890abcdef",
      sellerAddress: "0xFrankabcdef1234567890",
      price: 0.05,
      purchaseDate: "2024-01-19T16:45:00Z",
      status: "completed",
      transactionHash: "0x4567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234",
      usageCount: 1
    }
  ],
  analytics: {
    totalRevenue: "5.2 ETH",
    totalRemixes: 479,
    totalUsers: 1250,
    trendingIPs: 8,
    totalViews: 10450000,
    totalLicenses: 156,
    averageRevenuePerIP: "0.35 ETH",
    topEarningIP: "Pepe's Revenge - The Viral Sensation"
  }
};

// Setup demo data
export const setupDemoData = (): void => {
  try {
    // Save demo data to localStorage
    localStorage.setItem('forkyoudaddy_ips', JSON.stringify(WINNING_DEMO_DATA.ips));
    localStorage.setItem('users', JSON.stringify(WINNING_DEMO_DATA.users));
    localStorage.setItem('forkyoudaddy_licenses', JSON.stringify(WINNING_DEMO_DATA.licenses));
    localStorage.setItem('demo_analytics', JSON.stringify(WINNING_DEMO_DATA.analytics));
    localStorage.setItem('demo_mode', 'true');
    
    console.log('✅ Demo data setup complete!');
    console.log('📊 Demo Analytics:', WINNING_DEMO_DATA.analytics);
    console.log('🎨 Demo IPs:', WINNING_DEMO_DATA.ips.length);
    console.log('👥 Demo Users:', WINNING_DEMO_DATA.users.length);
    console.log('📜 Demo Licenses:', WINNING_DEMO_DATA.licenses.length);
  } catch (error) {
    console.error('❌ Error setting up demo data:', error);
  }
};

// Setup demo wallet
export const setupDemoWallet = (): void => {
  try {
    // Mock wallet for demo
    const demoWallet = {
      address: "0xAlice1234567890abcdef",
      balance: "2.5 ETH",
      network: "Basecamp Testnet"
    };
    
    localStorage.setItem('demo_wallet', JSON.stringify(demoWallet));
    console.log('✅ Demo wallet setup complete!');
  } catch (error) {
    console.error('❌ Error setting up demo wallet:', error);
  }
};

// Clear demo data
export const clearDemoData = (): void => {
  try {
    localStorage.removeItem('forkyoudaddy_ips');
    localStorage.removeItem('users');
    localStorage.removeItem('forkyoudaddy_licenses');
    localStorage.removeItem('demo_analytics');
    localStorage.removeItem('demo_mode');
    localStorage.removeItem('demo_wallet');
    
    console.log('✅ Demo data cleared!');
  } catch (error) {
    console.error('❌ Error clearing demo data:', error);
  }
};

// Check if demo mode is active
export const isDemoMode = (): boolean => {
  return localStorage.getItem('demo_mode') === 'true';
};

// Test demo data
export const testDemoData = () => {
  try {
    const ips = JSON.parse(localStorage.getItem('forkyoudaddy_ips') || '[]');
    const users = JSON.parse(localStorage.getItem('users') || '[]');
    const licenses = JSON.parse(localStorage.getItem('forkyoudaddy_licenses') || '[]');
    const analytics = JSON.parse(localStorage.getItem('demo_analytics') || '{}');
    
    return {
      ips,
      users,
      licenses,
      analytics,
      isDemoMode: isDemoMode()
    };
  } catch (error) {
    console.error('❌ Error testing demo data:', error);
    return null;
  }
};

// Get demo analytics
export const getDemoAnalytics = () => {
  try {
    return JSON.parse(localStorage.getItem('demo_analytics') || '{}');
  } catch (error) {
    console.error('❌ Error getting demo analytics:', error);
    return {};
  }
};

// Get trending IPs
export const getTrendingIPs = () => {
  try {
    const ips = JSON.parse(localStorage.getItem('forkyoudaddy_ips') || '[]');
    return ips.filter((ip: DemoIP) => ip.trending);
  } catch (error) {
    console.error('❌ Error getting trending IPs:', error);
    return [];
  }
};

// Get top earning IPs
export const getTopEarningIPs = () => {
  try {
    const ips = JSON.parse(localStorage.getItem('forkyoudaddy_ips') || '[]');
    return ips
      .sort((a: DemoIP, b: DemoIP) => parseFloat(b.revenue) - parseFloat(a.revenue))
      .slice(0, 5);
  } catch (error) {
    console.error('❌ Error getting top earning IPs:', error);
    return [];
  }
}; 